# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82ff302a9fc2e0ca381f524fb5776a4514df7772f1633c7f8203a1f4499ae32e4aefb7ccd058b8e782809b524a74670f062f1587a0635f5c2929ec67f072c53b

test:
  secret_key_base: 02139aa255bd2cd6129ab282afa4d7fe6a617441acac1a4946754dbc393a41fa95a2038824ddd2b19a7f2aa31ea40f25be13fd4ef0602c35d496f70ac08319d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
